const storiesData = [
  {
    "country": "MX",
    "name": "Parque Heroes",
    "story": "The legend says that many years ago, there was a beautiful young girl who lived in Aguascalientes. She was kind and gentle, and everyone who knew her loved her. One day, the girl was walking through Parque Heroes when she was attacked by a group of bandits. They robbed her and then beheaded her.\n\nHer headless body was found the next day, and the city was in mourning. The girl's parents were heartbroken, and they vowed to find her killer. However, the bandits were never caught.\n\nTo this day, her ghost is said to haunt Parque Heroes. She wanders the park at night, looking for her head. If you see her, it is said that you will be cursed.\n\nSome people believe that the legend is true, while others believe that it is just a story. However, there is no doubt that the legend of the beheaded girl is a popular one in Aguascalientes. It is a story that is passed down from generation to generation, and it continues to frighten people.",
    "latitude": "21.8807", 
    "longitude": "-102.2877",
  },
  {
    "country": "GB-SCT",
    "name": "Kelpie",
    "story": "A Kelpie is a mythical water creature often depicted as a shape-shifting horse that inhabits bodies of water such as rivers and lochs (lakes). According to the legend, the Kelpie is known to be quite deceptive and would sometimes appear as a beautiful horse to lure people, particularly children, into riding it. Once a person was on its back, the Kelpie's skin would become adhesive, preventing the victim from escaping, and it would then drag them into the water to devour them.",
    "latitude": "56.4907", 
    "longitude": "-4.2270",
  },
  {
    "country": "ID",
    "name" : "Babi Ngepet",
    "story": "Babi ngepet is believed to be the product of a person who practices pesugihan babi black magic. This type of magic involves a person surrendering their humanity in exchange for becoming rich instantly. The person is then transformed into a boar or allowing themselves to be possessed by a demon in the shape of a boar. It has similarities with the Western concept of a werewolf.",
    "latitude": "-7.5", 
    "longitude": " 110",
  },
  {
    "country": "US",
    "name" : "Gore Orphanage",
    "story": "A local legend in Northern Ohio, which refers to a supposedly haunted ruin near the city of Vermilion in Lorain County, Ohio.\n\nThe ruin is a building that formerly housed the Swift Mansion and, later, the Light of Hope Orphanage, and is the subject of local urban legends, whereby the violent deaths of young adults and children are alleged to have occurred. According to the urban legends, supernatural activity has occurred in the building since its closure.\n\nThe legend of the Gore Orphanage is thought to have originated in the early 1900s. The Swift Mansion was built in 1856 by John Swift, a wealthy industrialist. Swift died in 1890, and the mansion was inherited by his daughter, Mary Swift. Mary Swift opened the Light of Hope Orphanage in the mansion in 1901.\n\nThe Light of Hope Orphanage was a boarding school for orphaned and abandoned children. The children at the orphanage were reportedly subjected to physical and emotional abuse. In 1910, a fire broke out at the orphanage and killed several children. The fire was reportedly caused by arson, and the culprit was never caught.\n\nThe orphanage closed in 1911, and the building has been abandoned ever since. The building has been the subject of numerous reports of paranormal activity, including ghostly apparitions, disembodied voices, and unexplained noises.\n\nSome people believe that the ghosts of the children who died in the fire still haunt the building. Others believe that the ghosts are the spirits of the orphans who were abused at the orphanage.\n\nWhether or not the Gore Orphanage is actually haunted is a matter of debate. However, the legend of the Gore Orphanage continues to be a popular one in Northern Ohio.",
    "latitude": "41.3000", 
    "longitude": "-82.0000",
  },
  {
    "country": "GB", 
    "name": "The Wulver",
    "story": "The Wulver is a mythical creature from Orkney folklore. It is often depicted as a solitary and benevolent being, resembling a human with the lower half of its body resembling that of a wolf. The Wulver has a kind nature and is known for its fishing skills. It would leave freshly caught fish on the windowsills of those in need, providing sustenance without expecting anything in return. The Wulver is shy and avoids direct contact with humans.",
    "latitude": "58.9804",
    "longitude": "-3.2489",
  },
  {
    "country": "US", 
    "name": "Jackalope",
    "story": "The Jackalope is a creature from North American folklore, often described as a mythical hybrid between a rabbit and an antelope, with antler-like growths on its head. It is said to possess elusive and mischievous traits. While it is often considered a playful and whimsical creature, some variations of the tale attribute it with causing trouble and pranks.",
    "latitude": "37.0902",
    "longitude": "-95.7129",
  },
  {
    "country": "CF", 
    "name": "Mokele-mbembe",
    "story": "Mokele-mbembe is a legendary sauropod-like creature reported to inhabit the Congo River basin in Central Africa. It is often described as a large aquatic or semi-aquatic creature resembling a sauropod dinosaur. Sightings and reports of Mokele-mbembe have fueled speculation about the survival of prehistoric creatures in remote and unexplored regions.",
    "latitude": "-1.2921",
    "longitude": "23.3559",
  },
  {
    "country": "NZ", 
    "name": "The Poukai",
    "story": "The Poukai is a creature from the folklore of the Maori people of New Zealand. It is described as a giant bird with the ability to create strong winds. The Poukai was said to descend upon villages, causing havoc and stealing food. Its legend is often linked to the extinction of the Haast's eagle, a real-life large bird of prey.",
    "latitude": "-40.9006",
    "longitude": "174.8860",
  },
  {
    "country": "SE", 
    "name": "The Kraken",
    "story": "The Kraken is a legendary sea monster often depicted as a giant octopus or squid. It is said to dwell in the depths of the ocean and is known for its immense size and destructive power. The Kraken is often associated with tales of sailors encountering it while out at sea, with the creature's massive tentacles capable of dragging ships and sailors beneath the waves.",
    "latitude": "60.1282",
    "longitude": "18.6435",
  },
  {
    "country": "JP", 
    "name": "Shirime",
    "story": "Shirime is a creature from Japanese folklore. It is said to have the appearance of a person with no face, but instead, it has an eye located in the place of its anus. Despite its unsettling appearance, Shirime is often depicted as a harmless and even humorous creature, engaging in bizarre interactions with humans. It is known for surprising people by revealing its eye in a surprising and comical manner.",
    "latitude": "36.2048",
    "longitude": "138.2529",
  },
  {
    "country": "RU", 
    "name": "Baba Yaga",
    "story": "Baba Yaga is a witch-like figure from Slavic folklore. She is often portrayed as a hag who lives in a hut that stands on chicken legs and is surrounded by a fence made of bones. Baba Yaga is both feared and respected, as she possesses powerful magical abilities. She is known for her unpredictable nature and is sometimes depicted as a helper and sometimes as a hindrance to those who seek her out.",
    "latitude": "51.1657",
    "longitude": "10.4515",
  },
  {
    "country": "IE", 
    "name": "Faeries",
    "story": "Faeries, also known as fairies, are mythical creatures found in the folklore of various North European cultures. They are often depicted as supernatural beings with magical powers, living in forests, meadows, and other natural places. Faeries come in various forms and sizes, from tiny delicate beings to more human-like figures. They are known for their interactions with humans, sometimes offering blessings or playing pranks.",
    "latitude": "54.5260",
    "longitude": "15.2551",
  },
  {
    "country": "CA", 
    "name": "Wendigo",
    "story": "The Wendigo is a malevolent creature from the folklore of various indigenous cultures in North America, particularly among the Algonquian-speaking tribes. It is often described as a cannibalistic and supernatural being associated with winter, famine, and a strong craving for human flesh. The Wendigo is believed to embody greed and excess, and stories of its terror often serve as cautionary tales.",
    "latitude": "56.1304",
    "longitude": "-106.3468",
  },
];

module.exports = storiesData;
